import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import { Pet } from '../types/PetCare';
import { format, parseISO } from 'date-fns';

export async function exportPetsAsJSON(pets: Pet[]): Promise<void> {
  const json = JSON.stringify({ version: 1, exportedAt: new Date().toISOString(), pets }, null, 2);
  const uri = FileSystem.documentDirectory + 'petcare-backup.json';
  await FileSystem.writeAsStringAsync(uri, json, { encoding: FileSystem.EncodingType.UTF8 });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: 'application/json', dialogTitle: 'Export PetCare Data' });
  }
}

export async function importPetsFromJSON(): Promise<Pet[] | null> {
  try {
    const uri = FileSystem.documentDirectory + 'petcare-backup.json';
    const exists = await FileSystem.getInfoAsync(uri);
    if (!exists.exists) return null;
    const json = await FileSystem.readAsStringAsync(uri);
    const data = JSON.parse(json);
    if (Array.isArray(data.pets)) return data.pets as Pet[];
    return null;
  } catch {
    return null;
  }
}

export function buildHealthSummaryText(pet: Pet): string {
  const events = [...pet.healthEvents]
    .sort((a, b) => parseISO(b.date).getTime() - parseISO(a.date).getTime())
    .slice(0, 10)
    .map((e) => `• ${e.title} (${format(parseISO(e.date), 'dd MMM yyyy')})`)
    .join('\n');

  return [
    `🐾 ${pet.name} — Health Summary`,
    `Breed: ${pet.breed} | Weight: ${pet.weightKg} kg`,
    `Vet: ${pet.vet?.name || 'N/A'} — ${pet.vet?.phone || ''}`,
    '',
    'Recent Health Events:',
    events || 'None',
    '',
    `Generated by PetCare — ${format(new Date(), 'dd MMM yyyy')}`,
  ].join('\n');
}

export async function shareHealthSummary(pet: Pet): Promise<void> {
  const text = buildHealthSummaryText(pet);
  const uri = FileSystem.documentDirectory + `${pet.name}-summary.txt`;
  await FileSystem.writeAsStringAsync(uri, text);
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: 'text/plain' });
  }
}
