import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { format, parseISO } from 'date-fns';
import { Pet } from '../types/PetCare';

function formatDate(iso: string): string {
  try {
    return format(parseISO(iso), 'dd MMM yyyy');
  } catch {
    return iso;
  }
}

export async function exportPetPassportAsPDF(pet: Pet): Promise<void> {
  const vaccines = pet.healthEvents
    .filter((e) => e.type === 'vaccine')
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
    .slice(0, 5);

  const activeMeds = pet.medications ?? [];

  const vaccineRows = vaccines.length
    ? vaccines.map((v) => `<tr><td>${v.title}</td><td>${formatDate(v.date)}</td><td>${v.nextDueDate ? formatDate(v.nextDueDate) : '—'}</td></tr>`).join('')
    : '<tr><td colspan="3" style="color:#888">No vaccine records</td></tr>';

  const medRows = activeMeds.length
    ? activeMeds.map((m) => `<tr><td>${m.name}</td><td>${m.dosage}</td><td>${m.frequency}</td></tr>`).join('')
    : '<tr><td colspan="3" style="color:#888">No medications</td></tr>';

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: -apple-system, Arial, sans-serif; margin: 40px; color: #1a1a2e; }
    .header { display: flex; align-items: center; margin-bottom: 32px; border-bottom: 3px solid #6c63ff; padding-bottom: 16px; }
    .pet-avatar { width: 80px; height: 80px; border-radius: 40px; background: #e8e6ff; display: flex; align-items: center; justify-content: center; font-size: 40px; margin-right: 24px; }
    h1 { font-size: 28px; margin: 0; color: #6c63ff; }
    h2 { font-size: 16px; color: #888; margin: 4px 0 0; font-weight: normal; }
    .section { margin-bottom: 28px; }
    .section-title { font-size: 14px; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; color: #6c63ff; margin-bottom: 12px; border-bottom: 1px solid #e8e6ff; padding-bottom: 6px; }
    .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
    .info-item { background: #f8f7ff; padding: 12px; border-radius: 8px; }
    .info-label { font-size: 11px; color: #888; text-transform: uppercase; }
    .info-value { font-size: 15px; font-weight: 600; margin-top: 2px; }
    table { width: 100%; border-collapse: collapse; }
    th { background: #f0edff; padding: 10px; text-align: left; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; }
    td { padding: 10px; border-bottom: 1px solid #f0edff; font-size: 14px; }
    .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #bbb; border-top: 1px solid #f0edff; padding-top: 16px; }
    .passport-id { font-size: 11px; color: #aaa; margin-top: 4px; }
  </style>
</head>
<body>
  <div class="header">
    <div class="pet-avatar">🐾</div>
    <div>
      <h1>${pet.name}</h1>
      <h2>${pet.breed} · ${pet.type.charAt(0).toUpperCase() + pet.type.slice(1)} · ${pet.gender === 'male' ? '♂' : '♀'}</h2>
      <div class="passport-id">ID: ${pet.id.toUpperCase()} · Generated: ${format(new Date(), 'dd MMM yyyy')}</div>
    </div>
  </div>

  <div class="section">
    <div class="section-title">Basic Information</div>
    <div class="info-grid">
      <div class="info-item"><div class="info-label">Date of Birth</div><div class="info-value">${formatDate(pet.dateOfBirth)}</div></div>
      <div class="info-item"><div class="info-label">Weight</div><div class="info-value">${pet.weightKg} kg</div></div>
      <div class="info-item"><div class="info-label">Food Target</div><div class="info-value">${pet.foodTargetGrams} g/day</div></div>
      <div class="info-item"><div class="info-label">Water Target</div><div class="info-value">${pet.waterTargetServings} srv/day</div></div>
    </div>
  </div>

  <div class="section">
    <div class="section-title">Veterinarian</div>
    <div class="info-grid">
      <div class="info-item"><div class="info-label">Name</div><div class="info-value">${pet.vet.name || '—'}</div></div>
      <div class="info-item"><div class="info-label">Clinic</div><div class="info-value">${pet.vet.clinic || '—'}</div></div>
      <div class="info-item"><div class="info-label">Phone</div><div class="info-value">${pet.vet.phone || '—'}</div></div>
    </div>
  </div>

  <div class="section">
    <div class="section-title">Vaccination History</div>
    <table>
      <thead><tr><th>Vaccine</th><th>Date</th><th>Next Due</th></tr></thead>
      <tbody>${vaccineRows}</tbody>
    </table>
  </div>

  <div class="section">
    <div class="section-title">Active Medications</div>
    <table>
      <thead><tr><th>Medication</th><th>Dosage</th><th>Frequency</th></tr></thead>
      <tbody>${medRows}</tbody>
    </table>
  </div>

  <div class="footer">
    Generated by PetCare MVP · ${format(new Date(), 'dd MMM yyyy HH:mm')}
  </div>
</body>
</html>
  `;

  const { uri } = await Print.printToFileAsync({ html, base64: false });
  await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: `${pet.name} Passport` });
}
